language: python
python:
  - "2.7"
  - "3.6"

# for plugins that require UI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
  - pip uninstall -y pytest
  - pip install -r requirements.txt colorama
env:
  matrix:
  - PYTEST_VERSION=3.6.0 PLUGINCOMPAT_SITE=http://plugincompat.herokuapp.com
  global:
    secure: I7Lx3j8NZx29yHe2tgNyXQkbXVRDJDhmgYRH3N8Z9sYBOnhfuMAXYJhBn9xmlMFB6FzUs/+P5Ba0u9MO/P+bTqCz0fnkYH/3tC6NzOLxZHVtvnhgFftlUPgMNLmnwOKvpOaet7TpB1HYntjUGYR4watoqIKR6Wg2joTKgt3dlWE=
script:
  - python run.py

branches:
  only:
    - master
    - /feature-.*/

