language: python
python:
  - "2.7"
  - "3.5"

# for plugins that require UI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
  - pip uninstall -y pytest
  - pip install -r requirements.txt
env:
  - PYTEST_VERSION=2.9.2 PLUGINCOMPAT_SITE=http://plugincompat.herokuapp.com
  - PYTEST_VERSION=3.0.1 PLUGINCOMPAT_SITE=http://plugincompat.herokuapp.com
script: 
  - python run.py

branches:
  only:
    - master
    - /feature-.*/
  
